name: Build & Publish Debug APK

on:
  push:
    branches:
      - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Generate version.txt for Hub release
        run: ./gradlew generateVersionTxt
      - name: Releasing using Hub
        uses: valley-fordham/action-release-debugapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          APP_FOLDER: app
          RELEASE_TITLE: New Build
